### ISSUE TITLE
WebBrowserHelper.ClearCache Hangs for IE10

### ISSUE THREAD

**Issue by tvkrnsky** [FastSpring/FsprgEmbeddedStoreWin#2]
IE 10 appears to break the conditions which triggered an exit to the first while(true) loop for previous IE versions.  This effectively breaks the embedded store (and hangs apps) for all Windows 8 and a growing number of Windows 7 users.  Not sure what the "correct" way to fix it is, but changing to a for loop with a maximum number of iterations worked for me.

**Comment by rdewell** [comment]
Thanks, this should be fixed in the following commit:

https://github.com/FastSpring/FsprgEmbeddedStoreWin/commit/b6d18738a21501eb7eb7544347eeb94e85c4f530
