### ISSUE TITLE
Invalid XML Content Returned

### ISSUE THREAD

**Issue by developernotes** [FastSpring/FsprgEmbeddedStoreWin#3]
Hi,
We are working on integrating the FastSpring embedded store within both our Windows and OS X applications, however recently during testing of the Windows integration we noticed invalid XML being returned from the response representing a successful transaction.  In particular, there is a block of CSS that is being embedded within the XML.  Below is an example:

`<?xml version="1.0" encoding="UTF-8"?>
@namespace html url(http://www.w3.org/1999/xhtml); :root {                       font:small Verdana;        font-weight: bold;         padding: 2em;              padding-left:4em;       }                          * {                           display: block;            padding-left: 2em;      }                          html|style {                  display: none;          }                          html|span, html|a {           display: inline;           padding: 0;                font-weight: normal;       text-decoration: none;  }                          html|span.block {             display: block;         }                          *[html|hidden],            span.block[html|hidden] {     display: none;          }                          .expand {                     display: block;         }                          .expand:before {              content: '+';              color: red;                position: absolute;        left: -1em;             }  .collapse {                   display: block;         }                          .collapse:before {            content: '-';              color: red;                position: absolute;        left:-1em;              }                         
<!DOCTYPE plist SYSTEM "http://www.apple.com/DTDs/PropertyList-1.0.dtd" PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN">
<plist version="1.0">
<dict>
<key>OrderIsTest</key>
<true/>...`

Any ideas as to what might be causing this CSS fragment to be included in the XML response?  It fails to load the XML at the point at which it would process the XML into a `Plist` object.  Thanks!

**Comment by rdewell** [comment]
Hello,

Just to confirm a couple of things:
- You haven't seen this in OS X?
- What version of Windows are you testing on, and what version of Internet Explorer is installed?

Ryan

**Comment by developernotes** [comment]
Hi @rdewell 

> You haven't seen this in OS X?

Correct, this is only present as far as we've seen in the embedded Windows store.  The transformation to an `NSData` object appears to be working correctly on OS X.

> What version of Windows are you testing on, and what version of Internet Explorer is installed?

This is occurring on a development environment running Windows 8.1 Pro x64, with IE 11 (specifically 11.0.9600.17351).

**Comment by developernotes** [comment]
Hi @rdewell 

We've narrow down the issue on our side.  Our Windows application was taking advantage of [browser emulation](http://msdn.microsoft.com/en-us/library/ee330730%28VS.85%29.aspx#browser_emulation), which allows us to specify which version of IE should be used when rendering content within the WPF WebBrowser control.  Specifically, we were setting the following registry sub key:

`HKEY_CURRENT_USER\SOFTWARE\Microsoft\Internet Explorer\Main\FeatureControl\FEATURE_BROWSER_EMULATION`

with a key name of our binary executable name, and a DWORD value of `11001`.  We also tried running it with other values such as `11000`, and `10001`, however the FastSpring response always contained the same embedded CSS content.  Removing that registry key allowed the content to be returned without the embedded CSS and then properly processed.  I am not certain why that causes the returned content to differ when that key is set, but at the moment we can operate without explicitly setting that key.
